version: "3"

services:
  httpd:
    image: httpd
    container_name: chrislane_com
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    volumes:
      - ./config/httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./public/:/usr/local/apache2/htdocs
      - /var/log/httpd/error_log:/var/log/httpd/error_log
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chrislane-com.entrypoints=web"
      - "traefik.http.routers.chrislane-com.rule=Host(`www.chrislane.com`, `chrislane.com`)"
      - "traefik.http.routers.chrislane-com.middlewares=secured-hsts@file, ipfs@docker"
      - "traefik.http.routers.chrislane-com-secure.entrypoints=web-secure"
      - "traefik.http.routers.chrislane-com-secure.rule=Host(`www.chrislane.com`, `chrislane.com`)"
      - "traefik.http.routers.chrislane-com-secure.middlewares=secured-hsts@file, ipfs@docker"
      - "traefik.http.routers.chrislane-com-secure.tls=true"
      - "traefik.http.middlewares.ipfs.headers.customresponseheaders.X-Ipfs-Path=/ipns/chrislane.com/"
      - "traefik.docker.network=proxy"

  ipfs:
    image: ipfs/go-ipfs
    container_name: ipfs_chrislane_com
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    environment:
      IPFS_PROFILE: "lowpower"
    volumes:
      - ./data/ipfs/:/data/ipfs/
      - ./public/:/export/
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.ipfs-chrislane-com.entrypoints=ipfs-tcp"
      - "traefik.tcp.routers.ipfs-chrislane-com.rule=HostSNI(`*`)"
      - "traefik.tcp.services.ipfs-chrislane-com.loadbalancer.server.port=4001"
      - "traefik.udp.routers.ipfs-chrislane-com.entrypoints=ipfs-udp"
      - "traefik.udp.routers.ipfs-chrislane-com.rule=HostSNI(`*`)"
      - "traefik.udp.services.ipfs-chrislane-com.loadbalancer.server.port=4001"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true
